### ISSUE TITLE
0.8.2-beta not working

### ISSUE THREAD

**Issue by joestein** [sclasen/akka-kafka#18]
commitOffsets needs () at the end now since we added an optional param to it

[ERROR] [10/31/2014 14:58:09.515] [default-akka.actor.default-dispatcher-5] [ActorSystem(default)] Uncaught error from thread [default-akka.actor.default-dispatcher-5] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.NoSuchMethodError: kafka.consumer.ConsumerConnector.commitOffsets()V
	at com.sclasen.akka.kafka.BatchConnectorFSM$$anonfun$5.applyOrElse(BatchActors.scala:148)
	at com.sclasen.akka.kafka.BatchConnectorFSM$$anonfun$5.applyOrElse(BatchActors.scala:129)
	at com.sclasen.akka.kafka.BatchConnectorFSM$$anonfun$5.applyOrElse(BatchActors.scala:148)
	at com.sclasen.akka.kafka.BatchConnectorFSM$$anonfun$5.applyOrElse(BatchActors.scala:129)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at com.sclasen.akka.kafka.BatchConnectorFSM.processEvent(BatchActors.scala:60)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
	at akka.actor.FSM$class.processEvent(FSM.scala:604)
	at com.sclasen.akka.kafka.BatchConnectorFSM.processEvent(BatchActors.scala:60)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:598)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:592)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.sclasen.akka.kafka.BatchConnectorFSM.aroundReceive(BatchActors.scala:60)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at com.sclasen.akka.kafka.BatchConnectorFSM.aroundReceive(BatchActors.scala:60)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by kuhnen** [comment]
I think you can close this :)

**Comment by sclasen** [comment]
:+1:
